### ISSUE TITLE
Buildspec.yml calls dmake not make

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/auth0-custom-lock#207]
The provided buildspec.yml calls dmake which does not work inside of codebuild.  I've overridden it with the below and it now works.  Also can not call `bash make` because make is a binary.

```
version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - make build
  post_build:
    commands:
      - make deploy
      - echo done
      - exit 0
```
